# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "wink"
version = "0.1.0"
authors = ["jw"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
regex = "1"
derive-new = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"